### PR TITLE
remove boost, some cleanups

### LINKED ISSUE #2: 🏁 Windows CI
CI under Windows is currently failing due to some strange bug related to Boost (see e.g., [this CI run](https://github.com/lucasberent/qsatencoder/runs/5362475620?check_suite_focus=true)). 
Until this is fixed, only Ubuntu and macOS are supported.

### PR DESCRIPTION
**Pull request by lucasberent**
Fixes #2.

### CODE REVIEW

**Review by burgholzer — CHANGES_REQUESTED** [review]
Overall this LGTM. I just have some minor feedback.

File: src/SatEncoder.cpp [hunk 1]
```diff
@@ -539,4 +520,4 @@ void SatEncoder::Statistics::from_json(const json& j) {
     j.at("solvingTime").get_to(solvingTime);
     j.at("satConstructionTime").get_to(satConstructionTime);
     j.at("z3map").get_to(z3StatsMap);
-}
+}
```
Comment (burgholzer) [inline src/SatEncoder.cpp:523]: there is a newline missing at the end of this file

File: test/test_satencoder.cpp [hunk 2]
```diff
@@ -17,9 +17,8 @@ TEST_F(SatEncoderTest, CheckEqualWhenEqualRandomCircuits) {
     qc::CircuitOptimizer::flattenOperations(circOne);
     auto circTwo = circOne.clone();
 
-    SatEncoder               sat_encoder;
-    std::vector<std::string> inputs;
-    bool                     result = sat_encoder.testEqual(circOne, circTwo, inputs);
+    SatEncoder sat_encoder;
```
Comment (burgholzer) [inline test/test_satencoder.cpp:20]: Try to use consistent naming throughout the project.
```suggestion
    SatEncoder satEncoder;
```
Usually we use `camelCase`.
This is not the only place in the project where there is a mismatch in conventions, so please consider taking care of that.

File: include/SatEncoder.hpp [hunk 3]
```diff
@@ -55,37 +73,18 @@ class SatEncoder {
...
-
-        void applyH(unsigned long target);
-
-        void applyS(unsigned long target);
-
-        void printStateTableau();
+        void                                         applyCNOT(unsigned long control, unsigned long target);
+        void                                         applyH(unsigned long target);
+        void                                         applyS(unsigned long target);
+        void                                         printStateTableau();
```
Comment (burgholzer) [inline include/SatEncoder.hpp:87]: Code format should be fixed by running clang-format as indicated by the corresponding CI check.

**Review by burgholzer — APPROVED** [review]
LGTM
